#!/bin/sh
case "$1" in
  main)
    # only tested in arch linux.
    gcc -l readline -o sclisp sclisp.c
    ;;
  playground)
    gcc -l readline -o playground playground.c
    ;;
  playground-debug)
    gcc -save-temps -l readline -o playground playground.c
    ;;
  playground-objdump)
    gcc -l readline -ggdb -c playground.c
    objdump --source --full-contents --reloc playground.o
    ;;
  *)
    echo "Usage: $0 main | playground"
    ;;
esac
